### ISSUE TITLE
Create base version of app

### ISSUE THREAD

**Issue by turbaszek** [turbaszek/tnijto#1]
- [x] Main page with link generator
- [x] Allow custom links name
- [x] Use firebase as storage

**Comment by janusz-chludzinski** [comment]
Hi @turbaszek - could you elaborate bit more on `Main page with link generator`? is this some kind of UI?

**Comment by turbaszek** [comment]
@janusz-chludzinski exactly, #4 includes some simple UI where users can insert a link and get shortened one. I would like to keep it as simple as possible by this I mean:
- lightweight js and css
- no npm or other stuff
